openapi: "3.0.2"
info:
  title: BathLARP - Debriefs
  version: "1.0"
servers:
  - url: https://api.bathlarp.co.uk/v1/debriefs
paths:
  /:
    get:
      responses:
        "200":
          description: OK
