openapi: "3.0.2"
info:
  title: BathLARP - Larpers
  version: "1.0"
servers:
  - url: https://api.bathlarp.co.uk/v1/larpers
paths:
  /:
    get:
      responses:
        "200":
          description: OK
    post:
      responses:
        "200":
          description: OK
